<div class="ui-state-error"><?php echo $this->getVar('error') ?></div>
<form method="POST" action="">
    <table>
        <tr>
            <td>Email</td>
            <td>
                <input type="text" name="login[username]"/>
            </td>
        </tr>
        <td>Пароль</td>
        <td>
            <input type="password" name="login[password]"/>
        </td>
        </tr>
    </table>
    <button type="submit">Login</button>
</form>