<?php /** @var core_block_page $this */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<?php $this->renderChildHtml('head');?>
    <body>
<?php  ?>
<?php
    $this->renderChildHtml('header');
    $this->renderChildHtml('messages');
    $this->renderChildHtml('root');
    $this->renderChildHtml('footer');
?>

    </body>
</html>